//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orpheus.Desktop.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orpheus.Desktop.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orpheus Music Player.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orpheus.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library loading.
        /// </summary>
        public static string LibraryLoading {
            get {
                return ResourceManager.GetString("LibraryLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue empty.
        /// </summary>
        public static string QueueEmpty {
            get {
                return ResourceManager.GetString("QueueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing playing.
        /// </summary>
        public static string NothingPlaying {
            get {
                return ResourceManager.GetString("NothingPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00 / 00:00.
        /// </summary>
        public static string DefaultTime {
            get {
                return ResourceManager.GetString("DefaultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat All.
        /// </summary>
        public static string RepeatAll {
            get {
                return ResourceManager.GetString("RepeatAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat One.
        /// </summary>
        public static string RepeatOne {
            get {
                return ResourceManager.GetString("RepeatOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders - {1} tracks.
        /// </summary>
        public static string FoldersSummary {
            get {
                return ResourceManager.GetString("FoldersSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} queued.
        /// </summary>
        public static string QueuedSummary {
            get {
                return ResourceManager.GetString("QueuedSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kbps.
        /// </summary>
        public static string BitrateFmt {
            get {
                return ResourceManager.GetString("BitrateFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Folder Unknown&gt;.
        /// </summary>
        public static string FolderUnknown {
            get {
                return ResourceManager.GetString("FolderUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title Unknown&gt;.
        /// </summary>
        public static string TitleUnknown {
            get {
                return ResourceManager.GetString("TitleUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Artist Unknown&gt;.
        /// </summary>
        public static string ArtistUnknown {
            get {
                return ResourceManager.GetString("ArtistUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tracks · {1} playlists.
        /// </summary>
        public static string TracksAndPlaylists {
            get {
                return ResourceManager.GetString("TracksAndPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tracks.
        /// </summary>
        public static string TrackCount {
            get {
                return ResourceManager.GetString("TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} playlists.
        /// </summary>
        public static string PlaylistCount {
            get {
                return ResourceManager.GetString("PlaylistCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save queue as playlist.
        /// </summary>
        public static string SaveQueueAsPlaylist {
            get {
                return ResourceManager.GetString("SaveQueueAsPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3U Playlist.
        /// </summary>
        public static string M3UPlaylist {
            get {
                return ResourceManager.GetString("M3UPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLS Playlist.
        /// </summary>
        public static string PLSPlaylist {
            get {
                return ResourceManager.GetString("PLSPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Queue.
        /// </summary>
        public static string UnsavedQueue {
            get {
                return ResourceManager.GetString("UnsavedQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your play queue has been modified.
        ///Do you want to save it as a playlist before replacing it?.
        /// </summary>
        public static string UnsavedQueueMessage {
            get {
                return ResourceManager.GetString("UnsavedQueueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Orpheus.
        /// </summary>
        public static string ShowOrpheus {
            get {
                return ResourceManager.GetString("ShowOrpheus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Library.
        /// </summary>
        public static string OfflineLibrary {
            get {
                return ResourceManager.GetString("OfflineLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Radio.
        /// </summary>
        public static string SessionRadio {
            get {
                return ResourceManager.GetString("SessionRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Stream.
        /// </summary>
        public static string SessionStream {
            get {
                return ResourceManager.GetString("SessionStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer.
        /// </summary>
        public static string Equalizer {
            get {
                return ResourceManager.GetString("Equalizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find tracks, artists, or playlists.
        /// </summary>
        public static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        public static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute / Unmute.
        /// </summary>
        public static string MuteUnmute {
            get {
                return ResourceManager.GetString("MuteUnmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add library folder.
        /// </summary>
        public static string AddLibraryFolder {
            get {
                return ResourceManager.GetString("AddLibraryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library options.
        /// </summary>
        public static string LibraryOptions {
            get {
                return ResourceManager.GetString("LibraryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Files.
        /// </summary>
        public static string ShowFiles {
            get {
                return ResourceManager.GetString("ShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music folder.
        /// </summary>
        public static string AddMusicFolder {
            get {
                return ResourceManager.GetString("AddMusicFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Queue.
        /// </summary>
        public static string PlayQueue {
            get {
                return ResourceManager.GetString("PlayQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue options.
        /// </summary>
        public static string QueueOptions {
            get {
                return ResourceManager.GetString("QueueOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Queue as Playlist....
        /// </summary>
        public static string SaveQueueAsPlaylistMenu {
            get {
                return ResourceManager.GetString("SaveQueueAsPlaylistMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue.
        /// </summary>
        public static string ClearQueue {
            get {
                return ResourceManager.GetString("ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
         ///   Looks up a localized string similar to Title + Album.
         /// </summary>
         public static string ShowTitleAlbum {
             get {
                 return ResourceManager.GetString("ShowTitleAlbum", resourceCulture);
             }
         }
         
         /// <summary>
         ///   Looks up a localized string similar to File Name + Folder.
         /// </summary>
         public static string ShowFileNameFolder {
             get {
                 return ResourceManager.GetString("ShowFileNameFolder", resourceCulture);
             }
         }
         
         /// <summary>
         ///   Looks up a localized string similar to Title + Album → File Name + Folder.
         /// </summary>
         public static string ShowTitleAlbumWithFallback {
             get {
                 return ResourceManager.GetString("ShowTitleAlbumWithFallback", resourceCulture);
             }
         }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Secondary Text.
        /// </summary>
        public static string ShowSecondaryText {
            get {
                return ResourceManager.GetString("ShowSecondaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Queue.
        /// </summary>
        public static string RemoveFromQueue {
            get {
                return ResourceManager.GetString("RemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track List.
        /// </summary>
        public static string TrackList {
            get {
                return ResourceManager.GetString("TrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated from playlists and folders.
        /// </summary>
        public static string CuratedFromPlaylistsAndFolders {
            get {
                return ResourceManager.GetString("CuratedFromPlaylistsAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ColTitle {
            get {
                return ResourceManager.GetString("ColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ColArtist {
            get {
                return ResourceManager.GetString("ColArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string ColAlbum {
            get {
                return ResourceManager.GetString("ColAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string ColFilename {
            get {
                return ResourceManager.GetString("ColFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ColFile {
            get {
                return ResourceManager.GetString("ColFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track #.
        /// </summary>
        public static string ColTrackNumber {
            get {
                return ResourceManager.GetString("ColTrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc #.
        /// </summary>
        public static string ColDiscNumber {
            get {
                return ResourceManager.GetString("ColDiscNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string ColDisc {
            get {
                return ResourceManager.GetString("ColDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string ColYear {
            get {
                return ResourceManager.GetString("ColYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string ColGenre {
            get {
                return ResourceManager.GetString("ColGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        public static string ColBitrate {
            get {
                return ResourceManager.GetString("ColBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ColTime {
            get {
                return ResourceManager.GetString("ColTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string ColFormat {
            get {
                return ResourceManager.GetString("ColFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string ColTrackHash {
            get {
                return ResourceManager.GetString("ColTrackHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string SortFileName {
            get {
                return ResourceManager.GetString("SortFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string SortDuration {
            get {
                return ResourceManager.GetString("SortDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added.
        /// </summary>
        public static string SortDateAdded {
            get {
                return ResourceManager.GetString("SortDateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string SortAscending {
            get {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide missing title.
        /// </summary>
        public static string FilterHideMissingTitle {
            get {
                return ResourceManager.GetString("FilterHideMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide missing artist.
        /// </summary>
        public static string FilterHideMissingArtist {
            get {
                return ResourceManager.GetString("FilterHideMissingArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide missing album.
        /// </summary>
        public static string FilterHideMissingAlbum {
            get {
                return ResourceManager.GetString("FilterHideMissingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide missing genre.
        /// </summary>
        public static string FilterHideMissingGenre {
            get {
                return ResourceManager.GetString("FilterHideMissingGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide missing track #.
        /// </summary>
        public static string FilterHideMissingTrackNumber {
            get {
                return ResourceManager.GetString("FilterHideMissingTrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tray icon (minimize to tray on close).
        /// </summary>
        public static string EnableTrayIcon {
            get {
                return ResourceManager.GetString("EnableTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Variant.
        /// </summary>
        public static string ColorVariant {
            get {
                return ResourceManager.GetString("ColorVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Colors.
        /// </summary>
        public static string CustomColors {
            get {
                return ResourceManager.GetString("CustomColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom color overrides.
        /// </summary>
        public static string EnableCustomColorOverrides {
            get {
                return ResourceManager.GetString("EnableCustomColorOverrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Colors.
        /// </summary>
        public static string ApplyColors {
            get {
                return ResourceManager.GetString("ApplyColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts directory:.
        /// </summary>
        public static string LayoutsDirectory {
            get {
                return ResourceManager.GetString("LayoutsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Folders.
        /// </summary>
        public static string MusicFolders {
            get {
                return ResourceManager.GetString("MusicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the library database to clear all indexed tracks and folders..
        /// </summary>
        public static string ResetLibraryDescription {
            get {
                return ResourceManager.GetString("ResetLibraryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Library.
        /// </summary>
         public static string ResetLibrary {
            get {
                return ResourceManager.GetString("ResetLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan All.
        /// </summary>
        public static string RescanLibrary {
            get {
                return ResourceManager.GetString("RescanLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Output.
        /// </summary>
        public static string AudioOutput {
            get {
                return ResourceManager.GetString("AudioOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Device.
        /// </summary>
        public static string OutputDevice {
            get {
                return ResourceManager.GetString("OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Licenses.
        /// </summary>
        public static string OpenSourceLicenses {
            get {
                return ResourceManager.GetString("OpenSourceLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        public static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Music Folder.
        /// </summary>
        public static string SelectMusicFolder {
            get {
                return ResourceManager.GetString("SelectMusicFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0}....
        /// </summary>
        public static string ScanningFmt {
            get {
                return ResourceManager.GetString("ScanningFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan complete..
        /// </summary>
        public static string ScanComplete {
            get {
                return ResourceManager.GetString("ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting library....
        /// </summary>
         public static string ResettingLibrary {
            get {
                return ResourceManager.GetString("ResettingLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning library....
        /// </summary>
        public static string ScanningLibrary {
            get {
                return ResourceManager.GetString("ScanningLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library reset..
        /// </summary>
        public static string LibraryReset {
            get {
                return ResourceManager.GetString("LibraryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Could not read license file).
        /// </summary>
        public static string CouldNotReadLicense {
            get {
                return ResourceManager.GetString("CouldNotReadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Equalizer.
        /// </summary>
        public static string EnableEqualizer {
            get {
                return ResourceManager.GetString("EnableEqualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamp.
        /// </summary>
        public static string Preamp {
            get {
                return ResourceManager.GetString("Preamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 dB.
        /// </summary>
        public static string PreampDefault {
            get {
                return ResourceManager.GetString("PreampDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dB.
        /// </summary>
        public static string DecibelFmt {
            get {
                return ResourceManager.GetString("DecibelFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string PresetFlat {
            get {
                return ResourceManager.GetString("PresetFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string PresetRock {
            get {
                return ResourceManager.GetString("PresetRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        public static string PresetPop {
            get {
                return ResourceManager.GetString("PresetPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz.
        /// </summary>
        public static string PresetJazz {
            get {
                return ResourceManager.GetString("PresetJazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical.
        /// </summary>
        public static string PresetClassical {
            get {
                return ResourceManager.GetString("PresetClassical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic.
        /// </summary>
        public static string PresetElectronic {
            get {
                return ResourceManager.GetString("PresetElectronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip-Hop.
        /// </summary>
        public static string PresetHipHop {
            get {
                return ResourceManager.GetString("PresetHipHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocal.
        /// </summary>
        public static string PresetVocal {
            get {
                return ResourceManager.GetString("PresetVocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass Boost.
        /// </summary>
        public static string PresetBassBoost {
            get {
                return ResourceManager.GetString("PresetBassBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treble Boost.
        /// </summary>
        public static string PresetTrebleBoost {
            get {
                return ResourceManager.GetString("PresetTrebleBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudness.
        /// </summary>
        public static string PresetLoudness {
            get {
                return ResourceManager.GetString("PresetLoudness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headphones.
        /// </summary>
        public static string PresetHeadphones {
            get {
                return ResourceManager.GetString("PresetHeadphones", resourceCulture);
            }
        }
    }
}
